### PR TITLE
'Alexnet' Transfer learning model with 88% val accuracy

### PR DESCRIPTION
**Pull request by hemhemoh**
Hello, I am done using Alexnet on the images, kindly merge my pull request and assign it to me with a level, so it can reflect on the leaderboard

### CODE REVIEW

**Comment by Suvraneel** [comment]
@debamitr1012 
Please check the discord server announcements...
You need to add labels to merged PRs so that they get a score on leaderboard

Read [here](https://discord.com/channels/927533015364677672/934559642787414096/959357953524265000)

**Comment by debamitr1012** [comment]
Ok sure I will do it today Sent from Android deviceOn Apr 15, 2022 3:12 AM, Suvraneel Bhuin ***@***.***> wrote:
@debamitr1012
Please check the discord server announcements...
You need to add labels to merged PRs so that they get a score on leaderboard
Read here

**Comment by debamitr1012** [comment]
> @debamitr1012 Please check the discord server announcements... You need to add labels to merged PRs so that they get a score on leaderboard
> 
> Read [here](https://discord.com/channels/927533015364677672/934559642787414096/959357953524265000)

I will do it by today

**Comment by gurjeetsinghvirdee** [comment]
@debamitr1012 add these labels `GSSoC22` and `Level0 Level1 Level2 Level3` according to their work

**Comment by debamitr1012** [comment]
> @debamitr1012 add these labels `GSSoC22` and `Level0 Level1 Level2 Level3` according to their work

Ok i will do it by today

**Comment by hemhemoh** [comment]
> > @debamitr1012 add these labels `GSSoC22` and `Level0 Level1 Level2 Level3` according to their work
> 
> Ok i will do it by today 

This tasks can't be a level one issue please, It's more complex than that. Other repo's I worked on with similar issues assigned level 2. Can you please change it @debamitr1012

**Comment by debamitr1012** [comment]
> 

Ok sure wait a min am making it

**Pull request merged**
